name-template: 'v$RESOLVED_VERSION ğŸŒˆ'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
      - 'breaking change'
  minor:
    labels:
      - 'minor'
  default: patch

categories:
  - title: ğŸ† Highlights
    labels: highlight
  - title: âœ¨ Features
    labels:
      - feature
      - enhancement
  - title: ğŸš€ Performance improvements
    labels: performance
  - title: ğŸ› Bug Fixes
    labels:
      - fix
      - bugfix
      - bug

  - title: 'ğŸ§° Maintenance'
    labels: chore
  - title: ğŸ“– Documentation
    labels: documentation
  - title: ğŸ› ï¸ Other improvements
    labels: internal

exclude-labels:
  - skip changelog
  - release

replacers:
  # Remove conventional commits from titles
  - search: '/- (build|chore|ci|depr|docs|feat|fix|perf|refactor|release|test)(\(.*\))?(\!)?\: /g'
    replace: '- '

template: |
  $CHANGES
